/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface MatrixResultDTO
 */
export interface MatrixResultDTO {
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof MatrixResultDTO
     */
    'matrixA': Array<Array<number>>;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof MatrixResultDTO
     */
    'matrixB': Array<Array<number>>;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof MatrixResultDTO
     */
    'result': Array<Array<number>>;
    /**
     * 
     * @type {number}
     * @memberof MatrixResultDTO
     */
    'timeNs': number;
}

/**
 * MatrixControllerApi - axios parameter creator
 * @export
 */
export const MatrixControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} size 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMatrix: async (size: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'size' is not null or undefined
            assertParamExists('addMatrix', 'size', size)
            const localVarPath = `/matrix/addMatrix`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} size 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        multiplyMatrix: async (size: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'size' is not null or undefined
            assertParamExists('multiplyMatrix', 'size', size)
            const localVarPath = `/matrix/multiplyMatrix`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MatrixControllerApi - functional programming interface
 * @export
 */
export const MatrixControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MatrixControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} size 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addMatrix(size: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MatrixResultDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addMatrix(size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MatrixControllerApi.addMatrix']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} size 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async multiplyMatrix(size: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MatrixResultDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.multiplyMatrix(size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MatrixControllerApi.multiplyMatrix']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MatrixControllerApi - factory interface
 * @export
 */
export const MatrixControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MatrixControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} size 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMatrix(size: number, options?: any): AxiosPromise<MatrixResultDTO> {
            return localVarFp.addMatrix(size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} size 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        multiplyMatrix(size: number, options?: any): AxiosPromise<MatrixResultDTO> {
            return localVarFp.multiplyMatrix(size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MatrixControllerApi - object-oriented interface
 * @export
 * @class MatrixControllerApi
 * @extends {BaseAPI}
 */
export class MatrixControllerApi extends BaseAPI {
    /**
     * 
     * @param {number} size 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatrixControllerApi
     */
    public addMatrix(size: number, options?: RawAxiosRequestConfig) {
        return MatrixControllerApiFp(this.configuration).addMatrix(size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} size 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatrixControllerApi
     */
    public multiplyMatrix(size: number, options?: RawAxiosRequestConfig) {
        return MatrixControllerApiFp(this.configuration).multiplyMatrix(size, options).then((request) => request(this.axios, this.basePath));
    }
}



